"""The /graph page — graphify's self-contained codebase viz, re-served.

graph.html is a GENERATED artifact from the ./graphify-out volume, rebuilt
wholesale by /graphify, so everything site-specific is applied per request:
the privacy scrubs + node/edge drops (graph_scrub), the look — communities,
hexagons, no hover tooltips, line-count sizes (graph_style), and the shared
chrome (css, cyber fx, nav) injected here. Split out of routes_views.py so
both stay under the 500-line cap.
"""
import re
import hashlib
from pathlib import Path

from fastapi import Request
from fastapi.responses import HTMLResponse, Response

from routers import guest_protected
from pages import (
    _build_nav, _CHROME_LINK, _FONT_PRELOAD, _FAVICON, _APPLE_WEBAPP_META, _CRT_FX,
)
from auth import SESSION_TOKEN
from graph_scrub import (
    _redact_graph_nodes, _drop_graph_book_nodes, _drop_graph_moltbook_nodes,
    _drop_graph_vendor_nodes, _drop_graph_library_nodes, _drop_graph_inferred_edges,
)
from graph_style import (
    _restyle_graph_nodes, _drop_graph_tooltips,
    _merge_graph_communities, _fix_graph_stats, _size_graph_by_loc,
)


# /graph overlay assets live in web/ (graph-overlay.css/js) — not inline here.
# CSS = vertical-left nav + vis-network config-panel theme; JS = enable the live
# physics configurator. Injected at serve time so they survive graph.html rebuilds.
_GRAPH_OVERLAY_CSS = '<link rel="stylesheet" href="/graph-overlay.css?v=38">'
_GRAPH_OVERLAY_JS = '<script src="/graph-overlay.js?v=38"></script>'
# graphify's graph.html has no viewport meta — without it mobile renders at
# desktop width and scales everything down (tiny buttons/text).
_VIEWPORT_META = '<meta name="viewport" content="width=device-width, initial-scale=1">'


@guest_protected.get("/graph", response_class=HTMLResponse)
async def graph_page(request: Request):
    # Self-contained graphify viz from the ./graphify-out volume (regenerated by
    # /graphify). Guest-gated (Turnstile): the graph is just codebase structure;
    # sensitive node summaries are scrubbed by _redact_graph_nodes. chrome.css +
    # the overlay css/js (nav restyle + live physics panel) + the nav are all
    # injected here so they survive rebuilds; non-admins get the guest nav.
    p = Path("/app/graphify-out/graph.html")
    if not p.exists():
        return HTMLResponse(
            "<pre>graph.html not found. Run /graphify to build it.</pre>",
            status_code=404,
        )
    guest = request.cookies.get("session") != SESSION_TOKEN
    _fx = _CRT_FX
    page = p.read_text()
    # Serve vis-network from our own origin (immutable-cached, no third-party
    # RTT) and unify with /emet's 9.1.9 so both share one cached copy. Replace
    # the whole CDN tag (its SRI integrity hash is pinned to graphify's 9.1.6,
    # so a bare URL swap would fail the integrity check). Regex so it survives
    # graphify regenerating graph.html.
    page = re.sub(
        r'<script src="https://unpkg\.com/vis-network@.*?</script>',
        '<script src="/vendor/vis-network-9.1.9.min.js?v=1"></script>',
        page, count=1, flags=re.DOTALL,
    )
    page = _redact_graph_nodes(page)
    page = _drop_graph_book_nodes(page)
    page = _drop_graph_moltbook_nodes(page)
    page = _drop_graph_vendor_nodes(page)
    # Drop imported library/framework symbols (BaseModel, Request, ...) — not our
    # code, just clutter.
    page = _drop_graph_library_nodes(page)
    # Drop dashed (INFERRED, low-confidence) edges before the stats rewrite so the
    # edge count reflects reality — thins the physics/canvas load for a faster render.
    page = _drop_graph_inferred_edges(page)
    # Merge graphify's many fine-grained communities into <=12 dir-based groups
    # (after the drops) so each gets a distinct color — vis only has 10 palette
    # slots, so 56 communities collapse to indistinguishable color noise.
    page = _merge_graph_communities(page)
    # Size nodes by line count (from graph.json sibling) instead of degree.
    page = _size_graph_by_loc(page, p.with_name("graph.json"))
    # Header counts are baked pre-scrub; rewrite to the merged/dropped reality.
    page = _fix_graph_stats(page)
    # Disable vis-network's improvedLayout — the graph is too large for it to
    # position (it warns + costs perf). Patched here so it survives /graphify.
    page = page.replace(
        "{ nodes: nodesDS, edges: edgesDS }, {",
        "{ nodes: nodesDS, edges: edgesDS }, {\n  layout: { improvedLayout: false },",
        1,
    )
    # Hexagon nodes + bg-filled (coloured-outline) look, matching /emet; repoints
    # the neighbour-stripe colour to the border. After the merge so node colours exist.
    page = _restyle_graph_nodes(page)
    # No hover tooltips — drop `title:` from both DataSet mappers.
    page = _drop_graph_tooltips(page)
    page = page.replace("</head>", _VIEWPORT_META + _APPLE_WEBAPP_META + _FAVICON + _FONT_PRELOAD + _CHROME_LINK + _GRAPH_OVERLAY_CSS + "</head>", 1)
    page = page.replace("</body>", _fx + _build_nav("graph", guest=guest) + _GRAPH_OVERLAY_JS + "</body>", 1)
    # /graph has no extension so the no-cache middleware skips it, and the route
    # body changes whenever /graphify regenerates graph.html. Tag the rendered
    # bytes with a content-hash ETag + no-cache so the browser revalidates every
    # load: unchanged -> 304 (cheap), updated -> 200 fresh. Cache-busts on update.
    etag = '"%s"' % hashlib.md5(page.encode()).hexdigest()
    headers = {"Cache-Control": "no-cache", "ETag": etag}
    if request.headers.get("if-none-match") == etag:
        return Response(status_code=304, headers=headers)
    return HTMLResponse(page, headers=headers)
